google.charts.load('current', {
  'packages': ['geochart'],
});
google.charts.setOnLoadCallback(drawRegionsMap);

function drawRegionsMap() {
  var data = google.visualization.arrayToDataTable(gerarDados());

  var options = {
  };

  var chart = new google.visualization.GeoChart(document.getElementById('regions_div'));

  chart.draw(data, options);
}

function gerarDados() {

  let dados = [

    ['Country', 'Popularity'],
    ['Germany', 200],
    ['United States', 300],
    ['Brazil', 690],
    ['France', 600],
    ['RU', 700],
    ['China', 900],
    ['India', 800],
    ['Japan', 400],
    ['Mexico', 450],
    ['Australia', 250],
    ['South Korea', 350],
    ['Spain', 550],
    ['Indonesia', 270],
    ['Turkey', 380],
    ['Iran', 240],
    ['United Kingdom', 590],
    ['Italy', 520],
    ['Argentina', 200],
    ['South Africa', 180],
    ['Nigeria', 320],
    ['Egypt', 280],
    ['Saudi Arabia', 310],
    ['Pakistan', 230],
    ['Bangladesh', 210],
    ['Philippines', 330],
    ['Vietnam', 290],
    ['Ethiopia', 170],
    ['Democratic Republic of the Congo', 150],
    ['Thailand', 360],
    ['Myanmar', 190],
    ['Tanzania', 160],
    ['South Sudan', 140],
    ['Kenya', 130],
    ['Ukraine', 270],
    ['Algeria', 220],
    ['Sudan', 120],
    ['Iraq', 260],
    ['Poland', 410],
    ['Canada', 500],
    ['Morocco', 110],
    ['Uzbekistan', 100],
    ['Peru', 70],
    ['Malaysia', 330],
    ['Uganda', 90],
    ['Venezuela', 60],
    ['Nepal', 50],
    ['Ghana', 80],
    ['Yemen', 40],
    ['Mozambique', 30],
    ['Australia', 250],
    ['North Korea', 20],
    ['Taiwan', 430],
    ['Ivory Coast', 10],
    ['Syria', 120],
    ['Madagascar', 70],
    ['Cameroon', 60],
    ['Romania', 240],
    ['Chile', 320],
    ['Netherlands', 420],
    ['Kazakhstan', 110],
    ['Niger', 50],
    ['Burkina Faso', 40],
    ['Ecuador', 30],
    ['Guatemala', 20],
    ['Mali', 10],
    ['Cambodia', 5],
    ['Senegal', 5],
    ['Chad', 5],
    ['Zimbabwe', 5],
    ['Benin', 5],
    ['Burundi', 5],
    ['Rwanda', 5],
    ['Tunisia', 5],
    ['Bolivia', 5],
    ['Belgium', 5],
    ['Albania', 170],
    ['Angola', 120],
    ['Armenia', 190],
    ['Austria', 280],
    ['Azerbaijan', 210],
    ['Bahrain', 80],
    ['Bangladesh', 270],
    ['Belarus', 260],
    ['Belize', 20],
    ['Bhutan', 5],
    ['Bosnia and Herzegovina', 150],
    ['Botswana', 60],
    ['Brunei', 10],
    ['Bulgaria', 220],
    ['Cambodia', 80],
    ['Cameroon', 100],
    ['Cape Verde', 10],
    ['Central African Republic', 10],
    ['Chad', 40],
    ['Comoros', 5],
    ['Croatia', 190],
    ['Cyprus', 50],
    ['Czech Republic', 300],
    ['Denmark', 250],
    ['Djibouti', 5],
    ['Dominican Republic', 80],
    ['East Timor', 5],
    ['Ecuador', 110],
    ['El Salvador', 40],
    ['Equatorial Guinea', 5],
    ['Eritrea', 5],
    ['Estonia', 80],
    ['Eswatini (Swaziland)', 10],
    ['Finland', 200],
    ['Gabon', 30],
    ['Gambia', 5],
    ['Georgia', 120],
    ['Greece', 270],
    ['Guinea', 30],
    ['Guinea-Bissau', 5],
    ['Guyana', 10],
    ['Haiti', 20],
    ['Honduras', 50],
    ['Hungary', 240],
    ['Iceland', 50],
    ['Indonesia', 690],
    ['Iraq', 220],
    ['Ireland', 130],
    ['Israel', 240],
    ['Jamaica', 40],
    ['Jordan', 100],
    ['Kazakhstan', 210],
    ['Kenya', 180],
    ['Kiribati', 5],
    ['Kosovo', 40],
    ['Kuwait', 130],
    ['Kyrgyzstan', 30],
    ['Laos', 30],
    ['Latvia', 70],
    ['Lebanon', 150],
    ['Lesotho', 5],
    ['Liberia', 10],
    ['Libya', 70],
    ['Liechtenstein', 5],
    ['Lithuania', 100],
    ['Luxembourg', 20],
    ['Madagascar', 40],
    ['Malawi', 20],
    ['Maldives', 10],
    ['Mali', 60],
    ['Malta', 30],
    ['Marshall Islands', 5],
    ['Mauritania', 20],
    ['Mauritius', 30],
    ['Micronesia', 5],
    ['Moldova', 60],
    ['Monaco', 5],
    ['Mongolia', 30],
    ['Montenegro', 20],
    ['Morocco', 310],
    ['Mozambique', 40],
    ['Myanmar', 250],
    ['Namibia', 20],
    ['Nauru', 5],
    ['Nepal', 70],
    ['New Zealand', 130],
    ['Nicaragua', 30],
    ['Niger', 50],
    ['North Korea', 60],
    ['North Macedonia (formerly Macedonia)', 30],
    ['Norway', 180],
    ['Oman', 60],
    ['Pakistan', 380],
    ['Palau', 5],
    ['Palestine', 50],
    ['Panama', 50],
    ['Paraguay', 60],
    ['Peru', 200],
    ['Philippines', 420],
    ['Poland', 380],
    ['Portugal', 220],
    ['Qatar', 70],
    ['Romania', 290],
    ['Rwanda', 40],
    ['Saint Kitts and Nevis', 5],
    ['Saint Lucia', 10],
    ['Saint Vincent and the Grenadines', 10],
    ['Samoa', 5],
    ['San Marino', 5],
    ['Sao Tome and Principe', 5],
    ['Saudi Arabia', 450],
    ['Senegal', 70],
    ['Serbia', 120],
    ['Seychelles', 5],
    ['Sierra Leone', 20],
    ['Singapore', 120],
    ['Slovakia', 110],
    ['Slovenia', 60],
    ['Solomon Islands', 5],
    ['Somalia', 10],
    ['South Africa', 350],
    ['South Korea', 440],
    ['South Sudan', 10],
    ['Spain', 440],
    ['Sri Lanka', 70],
    ['Sudan', 60],
    ['Suriname', 10],
    ['Sweden', 220],
    ['Switzerland', 220],
    ['Syria', 80],
    ['Taiwan', 170],
    ['Tajikistan', 20],
    ['Tanzania', 90],
    ['Thailand', 320],
    ['Togo', 20],
    ['Tonga', 5],
    ['Trinidad and Tobago', 30],
    ['Tunisia', 110],
    ['Turkey', 530],
    ['Turkmenistan', 20],
    ['Tuvalu', 5],
    ['Uganda', 70],
    ['Ukraine', 190],
    ['United Arab Emirates', 200],
    ['Uruguay', 40],
    ['Uzbekistan', 80],
    ['Vanuatu', 5],
    ['Vatican City', 5],
    ['Venezuela', 280],
    ['Vietnam', 370],
    ['Yemen', 30],
    ['Zambia', 30],
    ['Zimbabwe', 30],

  ];

  return dados;

}